### ISSUE TITLE
No details on how to call fetched data

### ISSUE THREAD

**Issue by doughnet** [peXed/gridsome-source-directus#9]
After reviewing the readme there is no information on how to use the data retrieved from directus. I assume it is a {{ data.collection.item }} or similar? Would recommend adding it to readme info.

Also is the data available on ALL pages globally?

**Comment by peXed** [comment]
Hello @doughnet .

The plugin is a gridsome source plugin. It is available on all pages globally.
That information is already in the Gridsome documentation and therefor not in this project readme (because it is a key featuer of gridsome and the gridsome source plugins).

For more information, see: [https://gridsome.org/docs/querying-data/](https://gridsome.org/docs/querying-data/)
